version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/merged_properties
      - app-tmp:/app/tmp
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true
      - WEBSITE_SITE_NAME=DockerContainer
    shm_size: 4gb  # Increased from 2gb to 4gb
    mem_limit: 8g  # Add explicit memory limit
    cpus: 2        # Add CPU limit
    restart: unless-stopped

volumes:
  app-data:
  app-tmp: